; [pytest]
; addopts = --headed --browser=chromium
; testpaths = tests

[pytest]
addopts = --headed --browser=chromium
testpaths = tests

# Custom settings for test data
testdata_file = testdata/TestData.xlsx
testdata_sheet = Register