; [pytest]
; addopts = --headed --browser=chromium
; testpaths = tests

[pytest]
addopts = --headed --browser=chromium --alluredir=reports/allure-results --html=reports/report.html --self-contained-html
testpaths = src/test/tests
log_cli = true
log_cli_level = INFO
log_cli_format = %(asctime)s - %(levelname)s - %(message)s
log_cli_date_format = %Y-%m-%d %H:%M:%S

markers =
    smoke: critical smoke scenarios
    regression: regression scenarios
    contact: contacts module scenarios
    ui: user interface scenarios
    negative: negative validation scenarios
    edge: edge case scenarios
    functional: functional scenarios
    validation: validation scenarios
    ai: AI-related scenarios

# Custom settings for test data
testdata_file = src/resources/testdata/TestData.xlsx
testdata_sheet = Login
